#!/usr/bin/env python3
"""Build a SIAM-online source handoff from the stable local manuscript.

The project keeps ``paper/mesa_sifin_manuscript.tex`` in a plain article class
so it compiles on machines without SIAM's online-only class.  This script
generates the SIFIN/SIAM source variant that should compile once the official
``siamonline250211.cls`` macro package is placed next to the generated source
or on TeX's search path.
"""

from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
ARTICLE_SOURCE = ROOT / "paper" / "mesa_sifin_manuscript.tex"
SIAM_SOURCE = ROOT / "paper" / "mesa_sifin_manuscript_siam.tex"


def _extract_command(text: str, command: str) -> str:
    match = re.search(rf"\\{command}\{{(.+?)\}}", text, re.S)
    if not match:
        raise ValueError(f"missing \\{command}{{...}} in {ARTICLE_SOURCE}")
    return re.sub(r"\s+", " ", match.group(1)).strip()


def _extract_environment(text: str, environment: str) -> str:
    match = re.search(
        rf"\\begin\{{{re.escape(environment)}\}}(.*?)\\end\{{{re.escape(environment)}\}}",
        text,
        re.S,
    )
    if not match:
        raise ValueError(f"missing {environment!r} environment in {ARTICLE_SOURCE}")
    return match.group(1).strip()


def _extract_block(text: str, start_pattern: str, end_pattern: str, label: str) -> str:
    match = re.search(start_pattern + r"(.*?)" + end_pattern, text, re.S)
    if not match:
        raise ValueError(f"missing {label} block in {ARTICLE_SOURCE}")
    return re.sub(r"\s+", " ", match.group(1)).strip()


def build_siam_source(article_text: str) -> str:
    title = _extract_command(article_text, "title")
    author = _extract_command(article_text, "author")
    abstract = _extract_environment(article_text, "abstract")
    keywords = _extract_block(
        article_text,
        r"\\noindent\\textbf\{Keywords\.\}\s*",
        r"\\medskip",
        "Keywords",
    )
    msc = _extract_block(
        article_text,
        r"\\noindent\\textbf\{MSC\.\}\s*",
        r"\\section\{Introduction\}",
        "MSC",
    )
    body_match = re.search(r"\\section\{Introduction\}(.*)\\end\{document\}\s*$", article_text, re.S)
    if not body_match:
        raise ValueError(f"missing manuscript body in {ARTICLE_SOURCE}")
    body = body_match.group(1).strip()

    return rf"""\documentclass[review]{{siamonline250211}}
% Generated by scripts/build_siam_source.py from paper/mesa_sifin_manuscript.tex.
% Requires SIAM's official online-only multimedia macro package:
% https://epubs.siam.org/journal-authors
% Place siamonline250211.cls and siamplain.bst next to this file or on TEXINPUTS.

\usepackage{{amsmath,amssymb,mathtools,booktabs,graphicx,array,enumitem}}
\usepackage{{hyperref}}

\newtheorem{{theorem}}{{Theorem}}
\newtheorem{{proposition}}{{Proposition}}
\newtheorem{{assumption}}{{Assumption}}
\newtheorem{{remark}}{{Remark}}

\newcommand{{\E}}{{\mathbb{{E}}}}
\newcommand{{\R}}{{\mathbb{{R}}}}
\newcommand{{\cA}}{{\mathcal{{A}}}}
\newcommand{{\cU}}{{\mathcal{{U}}}}
\newcommand{{\Gammahat}}{{\widehat{{\Gamma}}}}

\headers{{Structural Hawkes Ambiguity}}{{{author}}}
\title{{{title}}}

% TODO before submission: replace the working author block with final author
% names, affiliations, ORCID identifiers, funding, and corresponding-author
% details in SIAM's preferred \thanks{{...}} format.
\author{{{author}}}

\begin{{document}}
\maketitle

\begin{{abstract}}
{abstract}
\end{{abstract}}

\begin{{keywords}}
{keywords}
\end{{keywords}}

\begin{{AMS}}
{msc}
\end{{AMS}}

\section{{Introduction}}

{body}

\end{{document}}
"""


def main() -> None:
    article_text = ARTICLE_SOURCE.read_text(encoding="utf-8")
    SIAM_SOURCE.write_text(build_siam_source(article_text), encoding="utf-8")
    print(f"wrote {SIAM_SOURCE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
